### PR TITLE
Fixing issue where multiple queries executed for a collection of cate…

### PR DESCRIPTION
**Pull request by edwinljacobs**
…gories, just load them all at once.

### CODE REVIEW

**Comment by aadmathijssen** [comment]
Thanks for fixing this issue, this makes rendering the category tree a lot faster!

I do have some questions and remarks, though:
1. When all categories are loaded in one collection, no additional attributes are added to the result (using `addAttributeToSelect`). This is great from a performance point of view, but there are two attributes that are still referenced in the code:
    1. `include_in_menu` in `\Emico_Tweakwise_Block_Catalog_Layer_Facet_Tree_Items::categoryShowInMenu`. However, this method does not seem to be used: it is only referenced in `Emico_Tweakwise_Block_Catalog_Layer_Facet_Tree_Items::showItem`, but that method isn’t used anywhere. Shouldn’t these methods be removed? If not, I think an `addAttributeToSelect(‘url_key’)` should be added to the collection.
    2. `url_key` in `\Emico_Tweakwise_Model_UrlBuilder_Strategy_CategoryStrategy::buildUrl` (line 52). This is only needed when `Emico_Tweakwise_Helper_Data::categoryAsLink`. So at least for that case, I think an `addAttributeToSelect(‘url_key’)` should be added; note that `joinUrlRewrite` does not add the `url_key` to the result).
2. The `Emico_Tweakwise_Helper_Data::getFilterCategory` method returns an instance of `Mage_Catalog_Model_Category` including all attributes or no attributes, depending on whether the `Emico_Tweakwise_Helper_Data::addToCategoryCollection` has been called or not. For consistency, wouldn’t it be better if the category collection that is created in `Emico_Tweakwise_Helper_Data::getFilterCategory` uses the same logic as in the `Emico_Tweakwise_Model_Layout_Observer::getMagentoCategories` method?

Could you please take a look at this?

Thanks.

**Comment by edwinljacobs** [comment]
Hi, happy to hear that category filter rendering is now faster!
We will look into your comments and keep you posted.

With kind regards

**Comment by edwinljacobs** [comment]
Update on your comment:

Regarding 1 (i and ii)
Agreed that url_key should be added to the collection, same for include_in_menu. They are referenced and therefor should be available. 

We will keep the methods
Emico_Tweakwise_Block_Catalog_Layer_Facet_Tree_Items::categoryShowInMenu
Emico_Tweakwise_Block_Catalog_Layer_Facet_Tree_Items::showItem

Reasons being that we do not want to break template overrides or custom rewrites although they are not directly referenced in the module or its base templates.

Regarding 2) Also agreed that this should be consistent we will adjust the code that loads the categories
(ie emico_tweakwise/layout_observer) to include ->addAttributeToSelect('*'). This will add the url_key and include_in_menu as well. Reason we choose the '*' is again for compatibility, the method is public after all.
The added '*' should not be a performance issue while loading category data from the flat tables.

Thanks for pointing these out.

With kind regards, Edwin Jacobs

**Comment by edwinljacobs** [comment]
Another update.

As commented in Tweakwise export The tag 1.11.3 is sadly not production ready, we understand that it is a bit "clumsy" to have released that. release 1.11.4 removed some features which are in beta but unfortunately included in the release. We suggest not to use release 1.11.3 but instead use 1.11.4

**Comment by aadmathijssen** [comment]
Hi Edwin,

Using `addAttributeToSelect('*')` instead of `addAttributeToSelect` for only the `url_key` and `include_in_menu` attribute does have an impact on performance: when loading 100 categories in one query, I have measured a decrease in performance of 35% in a production environment when using `addAttributeToSelect('*')`. When flat tables are not used, the performance drops by 45%.

To measure this, I have created a [Magento shell script](https://gist.github.com/aadmathijssen/1dbb529bd856fa24c360713a09bafb72):

```
$ php testCategoryLoad.php --help
testCategoryLoad.php --category CATEGORY_ID [--load-in-bulk] [--use-flat-table] [--restricted-attributes] [--add-url-rewrite]

Tests category load for the children of CATEGORY_ID analyzing the performance of the Emico_Tweakwise_Helper_Data::getFilterCategory method.
```

To test the version 1.11.3 functionality, use all the options `--load-in-bulk`, `--use-flat-table`, `--add-url-rewrite` and `--restricted-attributes` (although the last option adds `addAttributeToSelect` calls for the `url_key` and `include_in_menu` attributes instead of no calls at all).

The test the version 1.11.4 functionality, use the options `--load-in-bulk`, `--use-flat-table` and `--add-url-rewrite`.

Could you please only add the attributes that are actually used?

Thanks.

Aad

**Comment by edwinljacobs** [comment]
Hi Aad,

Thanks for providing your test script, we will look into it.

With kind regards, Edwin

**Comment by edwinljacobs** [comment]
I have tested your script against one of my development sites on my own machine (using 1.11.4) with the following results:

number of categories = 437 (All the children of category id 2 (store root category))
---- WITH RESTRICTION
This is the time output of the script together with the flags used.
0.22713303565979	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.22191596031189	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.22478795051575	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.22983503341675	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.23038005828857	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.2355968952179	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.22948312759399	--restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite --category 2

---- WITHOUT RESTRICTION
0.27167892456055 --load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.2771852016449	--load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.27534794807434	--load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.2682728767395	--load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.27325701713562	--load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.28359913825989	--load-in-bulk --use-flat-table --add-url-rewrite --category 2
0.28507113456726	--load-in-bulk --use-flat-table --add-url-rewrite --category 2

I also tested just the query time which resulted in the following (on average):
-- With restriction 0.137  --load-in-bulk --use-flat-table --add-url-rewrite
-- Without restriction 0.175 --restricted-attributes --load-in-bulk --use-flat-table --add-url-rewrite

Here --load-in-bulk can be assumed as default (using 1.11.4 again, do not use 1.11.3).
The same goes for --add-url-rewrite. We see that there is a small performance hit in the range of 0.045 seconds which is not nothing and can be attributed to query time. 

One thing noticed is that the performance hit exaggerates when loading less categories (the performance loss gets progressively worse (percentage wise) when loading less categories). Example loading 93 categories:

This is just query time.
with restriction: 0.025 (on average)
without restriction: 0.014 (on average) 

We see percentage wise more performance loss, note that this is subject to more variance. Obviously the total time spent is less. But this is a more "common" use case.

As is, this is a minor issue and tag 1.11.4 can therefor be used and is still a major upgrade over tag 1.11.2 where each category is retrieved individually. Nevertheless we feel that if we can make every site using this module faster by incorporating the suggested changes,
namely: replace 
->addAttributeToSelect('*') 
with 
->addAttributeToSelect(['include_in_menu', 'url_key']),

then we should do so. As such, we created a new pull request.

These changes will be reviewed soon and hopefully merged.

**Comment by edwinljacobs** [comment]
This is now available in v1.11.5

**Pull request merged**
